server:
  port: 8014

spring:
  redis:
    host: redis-headless.redis.svc.cluster.local
    password: 123456
    port: 6379
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
    timeout: 0

  kafka:
    bootstrap-servers: kafka-headless.kafka.svc.cluster.local:9092
    producer:
      # 重试次数
      retries: 0
      # 应答级别:多少个分区副本备份完成时向生产者发送ack确认(可选0、1、all/-1)
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        delivery:
          timeout:
            ms: 5300
        linger:
          ms: 200
        request:
          timeout:
            ms: 5000
    consumer:
      auto-offset-reset: latest                           #最早未被消费的offset earliest
      max-poll-records: 2000                              #批量消费一次最大拉取的数据量
      enable-auto-commit: true                            #是否开启自动提交
      auto-commit-interval: 1000                          #自动提交的间隔时间
      session-timeout: 20000                              #连接超时时间
      max-poll-interval: 15000                            #手动提交设置与poll的心跳数,如果消息队列中没有消息，等待毫秒后，调用poll()方法。如果队列中有消息，立即消费消息，每次消费的消息的多少可以通过max.poll.records配置。
      max-partition-fetch-bytes: 52428800                 #设置拉取数据的大小,50M

